// Mocks generated by Mockito 5.4.6 from annotations
// in finanzbegleiter/test/models/models/pagebuilder/pagebuilder_paint_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:bloc/bloc.dart' as _i9;
import 'package:finanzbegleiter/application/pagebuilder/pagebuilder_bloc.dart'
    as _i6;
import 'package:finanzbegleiter/domain/entities/pagebuilder/pagebuilder_local_history.dart'
    as _i5;
import 'package:finanzbegleiter/domain/repositories/landing_page_repository.dart'
    as _i2;
import 'package:finanzbegleiter/domain/repositories/pagebuilder_repository.dart'
    as _i3;
import 'package:finanzbegleiter/domain/repositories/user_repository.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeLandingPageRepository_0 extends _i1.SmartFake
    implements _i2.LandingPageRepository {
  _FakeLandingPageRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePagebuilderRepository_1 extends _i1.SmartFake
    implements _i3.PagebuilderRepository {
  _FakePagebuilderRepository_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserRepository_2 extends _i1.SmartFake
    implements _i4.UserRepository {
  _FakeUserRepository_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePagebuilderLocalHistory_3 extends _i1.SmartFake
    implements _i5.PagebuilderLocalHistory {
  _FakePagebuilderLocalHistory_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PagebuilderBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockPagebuilderBloc extends _i1.Mock implements _i6.PagebuilderBloc {
  MockPagebuilderBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LandingPageRepository get landingPageRepo => (super.noSuchMethod(
        Invocation.getter(#landingPageRepo),
        returnValue: _FakeLandingPageRepository_0(
          this,
          Invocation.getter(#landingPageRepo),
        ),
      ) as _i2.LandingPageRepository);

  @override
  _i3.PagebuilderRepository get pageBuilderRepo => (super.noSuchMethod(
        Invocation.getter(#pageBuilderRepo),
        returnValue: _FakePagebuilderRepository_1(
          this,
          Invocation.getter(#pageBuilderRepo),
        ),
      ) as _i3.PagebuilderRepository);

  @override
  _i4.UserRepository get userRepo => (super.noSuchMethod(
        Invocation.getter(#userRepo),
        returnValue: _FakeUserRepository_2(
          this,
          Invocation.getter(#userRepo),
        ),
      ) as _i4.UserRepository);

  @override
  _i5.PagebuilderLocalHistory get localHistory => (super.noSuchMethod(
        Invocation.getter(#localHistory),
        returnValue: _FakePagebuilderLocalHistory_3(
          this,
          Invocation.getter(#localHistory),
        ),
      ) as _i5.PagebuilderLocalHistory);

  @override
  bool get isUndoRedoOperation => (super.noSuchMethod(
        Invocation.getter(#isUndoRedoOperation),
        returnValue: false,
      ) as bool);

  @override
  set isUndoRedoOperation(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #isUndoRedoOperation,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.PagebuilderState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _i7.dummyValue<_i6.PagebuilderState>(
          this,
          Invocation.getter(#state),
        ),
      ) as _i6.PagebuilderState);

  @override
  _i8.Stream<_i6.PagebuilderState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i8.Stream<_i6.PagebuilderState>.empty(),
      ) as _i8.Stream<_i6.PagebuilderState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  bool canUndo() => (super.noSuchMethod(
        Invocation.method(
          #canUndo,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool canRedo() => (super.noSuchMethod(
        Invocation.method(
          #canRedo,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  void add(_i6.PagebuilderEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i6.PagebuilderEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i6.PagebuilderState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i6.PagebuilderEvent>(
    _i9.EventHandler<E, _i6.PagebuilderState>? handler, {
    _i9.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i9.Transition<_i6.PagebuilderEvent, _i6.PagebuilderState>?
              transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onDone(
    _i6.PagebuilderEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #onDone,
          [
            event,
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void onChange(_i9.Change<_i6.PagebuilderState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
