// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsProd {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHxAj-YqzpN4D0RSOmtcVqesfonhAOb8s',
    appId: '1:962239137198:web:cae5870aef9e767b44743f',
    messagingSenderId: '962239137198',
    projectId: 'finanzwegbegleiter',
    authDomain: 'finanzwegbegleiter.firebaseapp.com',
    storageBucket: 'finanzwegbegleiter.appspot.com',
    measurementId: 'G-CQVYXTTT1Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYug60Zd671UX-bT9RxV3GMYpvPH33HGk',
    appId: '1:962239137198:android:8e8af086ccdef55544743f',
    messagingSenderId: '962239137198',
    projectId: 'finanzwegbegleiter',
    storageBucket: 'finanzwegbegleiter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH3bzKrA1fRJaCvp5U5OLVxEDpKdmo1AU',
    appId: '1:962239137198:ios:1179d0d3d875c4ba44743f',
    messagingSenderId: '962239137198',
    projectId: 'finanzwegbegleiter',
    storageBucket: 'finanzwegbegleiter.appspot.com',
    iosBundleId: 'de.trustleap.app',
  );

}