// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsStaging {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUZcZ7P98X28iFRxKOXlGsK0XH4FrcMuU',
    appId: '1:326519245330:web:c77040d973d1308624e6cb',
    messagingSenderId: '326519245330',
    projectId: 'trustleap-staging',
    authDomain: 'trustleap-staging.firebaseapp.com',
    storageBucket: 'trustleap-staging.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiPDl3Fy9f6yGrwBNROdmC32GdMhsv0pU',
    appId: '1:326519245330:android:6d87caf930eb145924e6cb',
    messagingSenderId: '326519245330',
    projectId: 'trustleap-staging',
    storageBucket: 'trustleap-staging.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh8agQbVtDjB5HyRXO1iWHq0MBi0TFPMY',
    appId: '1:326519245330:ios:5dbcbf8e1394ba9924e6cb',
    messagingSenderId: '326519245330',
    projectId: 'trustleap-staging',
    storageBucket: 'trustleap-staging.firebasestorage.app',
    iosBundleId: 'de.trustleap.app.staging',
  );

}