import 'package:flutter_test/flutter_test.dart';
import 'package:finanzbegleiter/domain/entities/pagebuilder/pagebuilder_contact_form_properties.dart';
import 'package:finanzbegleiter/domain/entities/pagebuilder/pagebuilder_textfield_properties.dart';
import 'package:finanzbegleiter/domain/entities/pagebuilder/pagebuilder_button_properties.dart';
import 'package:finanzbegleiter/domain/entities/pagebuilder/pagebuilder_border.dart';
import 'package:finanzbegleiter/domain/entities/pagebuilder/pagebuilder_text_properties.dart';
import 'package:flutter/material.dart';
import 'package:finanzbegleiter/domain/entities/pagebuilder/pagebuilder_paint.dart';
import 'package:finanzbegleiter/domain/entities/pagebuilder/responsive/pagebuilder_responsive_or_constant.dart';

void main() {
  group("PagebuilderContactFormProperties_CopyWith", () {
    test(
        "set nameTextFieldProperties and buttonProperties with copyWith should set nameTextFieldProperties and buttonProperties for resulting object",
        () {
      // Given
      final model = PageBuilderContactFormProperties(
          email: "test@test.de",
          nameTextFieldProperties: PageBuilderTextFieldProperties(
              width: const PagebuilderResponsiveOrConstant.constant(200.0),
              minLines: 1,
              maxLines: 1,
              isRequired: true,
              backgroundColor: null,
              borderColor: null,
              placeHolderTextProperties: PageBuilderTextProperties(
                  text: "test",
                  fontSize: const PagebuilderResponsiveOrConstant.constant(12.0),
                  fontFamily: "Poppins",
                  lineHeight: null,
                  letterSpacing: null,
                  textShadow: null,
                  color: null,
                  alignment: null),
              textProperties: PageBuilderTextProperties(
                  text: "test",
                  fontSize: const PagebuilderResponsiveOrConstant.constant(12.0),
                  fontFamily: "Poppins",
                  lineHeight: null,
                  letterSpacing: null,
                  textShadow: null,
                  color: null,
                  alignment: null)),
          emailTextFieldProperties: PageBuilderTextFieldProperties(
              width: const PagebuilderResponsiveOrConstant.constant(300.0),
              minLines: 1,
              maxLines: 1,
              isRequired: true,
              backgroundColor: null,
              borderColor: null,
              placeHolderTextProperties: PageBuilderTextProperties(
                  text: "test",
                  fontSize: const PagebuilderResponsiveOrConstant.constant(12.0),
                  fontFamily: "Poppins",
                  lineHeight: null,
                  letterSpacing: null,
                  textShadow: null,
                  color: null,
                  alignment: null),
              textProperties: PageBuilderTextProperties(
                  text: "test",
                  fontSize: const PagebuilderResponsiveOrConstant.constant(12.0),
                  fontFamily: "Poppins",
                  lineHeight: null,
                  letterSpacing: null,
                  textShadow: null,
                  color: null,
                  alignment: null)),
          phoneTextFieldProperties: PageBuilderTextFieldProperties(
              width: const PagebuilderResponsiveOrConstant.constant(300.0),
              minLines: 1,
              maxLines: 1,
              isRequired: true,
              backgroundColor: null,
              borderColor: null,
              placeHolderTextProperties: PageBuilderTextProperties(
                  text: "test",
                  fontSize: const PagebuilderResponsiveOrConstant.constant(12.0),
                  fontFamily: "Poppins",
                  lineHeight: null,
                  letterSpacing: null,
                  textShadow: null,
                  color: null,
                  alignment: null),
              textProperties: PageBuilderTextProperties(
                  text: "test",
                  fontSize: const PagebuilderResponsiveOrConstant.constant(12.0),
                  fontFamily: "Poppins",
                  lineHeight: null,
                  letterSpacing: null,
                  textShadow: null,
                  color: null,
                  alignment: null)),
          messageTextFieldProperties: PageBuilderTextFieldProperties(
              width: const PagebuilderResponsiveOrConstant.constant(300.0),
              minLines: 1,
              maxLines: 1,
              isRequired: true,
              backgroundColor: null,
              borderColor: null,
              placeHolderTextProperties: PageBuilderTextProperties(
                  text: "test",
                  fontSize: const PagebuilderResponsiveOrConstant.constant(12.0),
                  fontFamily: "Poppins",
                  lineHeight: null,
                  letterSpacing: null,
                  textShadow: null,
                  color: null,
                  alignment: null),
              textProperties: PageBuilderTextProperties(
                  text: "test",
                  fontSize: const PagebuilderResponsiveOrConstant.constant(12.0),
                  fontFamily: "Poppins",
                  lineHeight: null,
                  letterSpacing: null,
                  textShadow: null,
                  color: null,
                  alignment: null)),
          buttonProperties: PageBuilderButtonProperties(
              width: const PagebuilderResponsiveOrConstant.constant(200),
              height: const PagebuilderResponsiveOrConstant.constant(100),
              border: const PagebuilderBorder(radius: 12.0, width: null, color: null),
              backgroundPaint: null,
              textProperties: null));
      final expectedResult = PageBuilderContactFormProperties(
          email: "test@test.de",
          nameTextFieldProperties: PageBuilderTextFieldProperties(
              width: const PagebuilderResponsiveOrConstant.constant(300.0),
              minLines: 1,
              maxLines: 1,
              isRequired: true,
              backgroundColor: null,
              borderColor: null,
              placeHolderTextProperties: PageBuilderTextProperties(
                  text: "test",
                  fontSize: const PagebuilderResponsiveOrConstant.constant(12.0),
                  fontFamily: "Poppins",
                  lineHeight: null,
                  letterSpacing: null,
                  textShadow: null,
                  color: null,
                  alignment: null),
              textProperties: PageBuilderTextProperties(
                  text: "test",
                  fontSize: const PagebuilderResponsiveOrConstant.constant(12.0),
                  fontFamily: "Poppins",
                  lineHeight: null,
                  letterSpacing: null,
                  textShadow: null,
                  color: null,
                  alignment: null)),
          emailTextFieldProperties: PageBuilderTextFieldProperties(
              width: const PagebuilderResponsiveOrConstant.constant(300.0),
              minLines: 1,
              maxLines: 1,
              isRequired: true,
              backgroundColor: null,
              borderColor: null,
              placeHolderTextProperties: PageBuilderTextProperties(
                  text: "test",
                  fontSize: const PagebuilderResponsiveOrConstant.constant(12.0),
                  fontFamily: "Poppins",
                  lineHeight: null,
                  letterSpacing: null,
                  textShadow: null,
                  color: null,
                  alignment: null),
              textProperties: PageBuilderTextProperties(
                  text: "test",
                  fontSize: const PagebuilderResponsiveOrConstant.constant(12.0),
                  fontFamily: "Poppins",
                  lineHeight: null,
                  letterSpacing: null,
                  textShadow: null,
                  color: null,
                  alignment: null)),
          phoneTextFieldProperties: PageBuilderTextFieldProperties(
              width: const PagebuilderResponsiveOrConstant.constant(300.0),
              minLines: 1,
              maxLines: 1,
              isRequired: true,
              backgroundColor: null,
              borderColor: null,
              placeHolderTextProperties: PageBuilderTextProperties(
                  text: "test",
                  fontSize: const PagebuilderResponsiveOrConstant.constant(12.0),
                  fontFamily: "Poppins",
                  lineHeight: null,
                  letterSpacing: null,
                  textShadow: null,
                  color: null,
                  alignment: null),
              textProperties: PageBuilderTextProperties(
                  text: "test",
                  fontSize: const PagebuilderResponsiveOrConstant.constant(12.0),
                  fontFamily: "Poppins",
                  lineHeight: null,
                  letterSpacing: null,
                  textShadow: null,
                  color: null,
                  alignment: null)),
          messageTextFieldProperties: PageBuilderTextFieldProperties(
              width: const PagebuilderResponsiveOrConstant.constant(300.0),
              minLines: 1,
              maxLines: 1,
              isRequired: true,
              backgroundColor: null,
              borderColor: null,
              placeHolderTextProperties: PageBuilderTextProperties(
                  text: "test",
                  fontSize: const PagebuilderResponsiveOrConstant.constant(12.0),
                  fontFamily: "Poppins",
                  lineHeight: null,
                  letterSpacing: null,
                  textShadow: null,
                  color: null,
                  alignment: null),
              textProperties: PageBuilderTextProperties(
                  text: "test",
                  fontSize: const PagebuilderResponsiveOrConstant.constant(12.0),
                  fontFamily: "Poppins",
                  lineHeight: null,
                  letterSpacing: null,
                  textShadow: null,
                  color: null,
                  alignment: null)),
          buttonProperties: PageBuilderButtonProperties(
              width: const PagebuilderResponsiveOrConstant.constant(200),
              height: const PagebuilderResponsiveOrConstant.constant(100),
              border: const PagebuilderBorder(radius: 16, width: null, color: null),
              backgroundPaint: null,
              textProperties: null));
      // When
      final result = model.copyWith(
          nameTextFieldProperties: PageBuilderTextFieldProperties(
              width: const PagebuilderResponsiveOrConstant.constant(300.0),
              minLines: 1,
              maxLines: 1,
              isRequired: true,
              backgroundColor: null,
              borderColor: null,
              placeHolderTextProperties: PageBuilderTextProperties(
                  text: "test",
                  fontSize: const PagebuilderResponsiveOrConstant.constant(12.0),
                  fontFamily: "Poppins",
                  lineHeight: null,
                  letterSpacing: null,
                  textShadow: null,
                  color: null,
                  alignment: null),
              textProperties: PageBuilderTextProperties(
                  text: "test",
                  fontSize: const PagebuilderResponsiveOrConstant.constant(12.0),
                  fontFamily: "Poppins",
                  lineHeight: null,
                  letterSpacing: null,
                  textShadow: null,
                  color: null,
                  alignment: null)),
          buttonProperties: PageBuilderButtonProperties(
              width: const PagebuilderResponsiveOrConstant.constant(200),
              height: const PagebuilderResponsiveOrConstant.constant(100),
              border: const PagebuilderBorder(radius: 16, width: null, color: null),
              backgroundPaint: null,
              textProperties: null));
      // Then
      expect(result, expectedResult);
    });
  });

  group("PagebuilderContactFormProperties_Props", () {
    test("check if value equality works", () {
      // Given
      final properties1 = PageBuilderContactFormProperties(
          email: "test@test.de",
          nameTextFieldProperties: PageBuilderTextFieldProperties(
              width: const PagebuilderResponsiveOrConstant.constant(200.0),
              minLines: 1,
              maxLines: 1,
              isRequired: true,
              backgroundColor: null,
              borderColor: null,
              placeHolderTextProperties: PageBuilderTextProperties(
                  text: "test",
                  fontSize: const PagebuilderResponsiveOrConstant.constant(12.0),
                  fontFamily: "Poppins",
                  lineHeight: null,
                  letterSpacing: null,
                  textShadow: null,
                  color: null,
                  alignment: null),
              textProperties: PageBuilderTextProperties(
                  text: "test",
                  fontSize: const PagebuilderResponsiveOrConstant.constant(12.0),
                  fontFamily: "Poppins",
                  lineHeight: null,
                  letterSpacing: null,
                  textShadow: null,
                  color: null,
                  alignment: null)),
          emailTextFieldProperties: PageBuilderTextFieldProperties(
              width: const PagebuilderResponsiveOrConstant.constant(300.0),
              minLines: 1,
              maxLines: 1,
              isRequired: true,
              backgroundColor: null,
              borderColor: null,
              placeHolderTextProperties: PageBuilderTextProperties(
                  text: "test",
                  fontSize: const PagebuilderResponsiveOrConstant.constant(12.0),
                  fontFamily: "Poppins",
                  lineHeight: null,
                  letterSpacing: null,
                  textShadow: null,
                  color: null,
                  alignment: null),
              textProperties: PageBuilderTextProperties(
                  text: "test",
                  fontSize: const PagebuilderResponsiveOrConstant.constant(12.0),
                  fontFamily: "Poppins",
                  lineHeight: null,
                  letterSpacing: null,
                  textShadow: null,
                  color: null,
                  alignment: null)),
          phoneTextFieldProperties: PageBuilderTextFieldProperties(
              width: const PagebuilderResponsiveOrConstant.constant(300.0),
              minLines: 1,
              maxLines: 1,
              isRequired: true,
              backgroundColor: null,
              borderColor: null,
              placeHolderTextProperties: PageBuilderTextProperties(
                  text: "test",
                  fontSize: const PagebuilderResponsiveOrConstant.constant(12.0),
                  fontFamily: "Poppins",
                  lineHeight: null,
                  letterSpacing: null,
                  textShadow: null,
                  color: null,
                  alignment: null),
              textProperties: PageBuilderTextProperties(
                  text: "test",
                  fontSize: const PagebuilderResponsiveOrConstant.constant(12.0),
                  fontFamily: "Poppins",
                  lineHeight: null,
                  letterSpacing: null,
                  textShadow: null,
                  color: null,
                  alignment: null)),
          messageTextFieldProperties: PageBuilderTextFieldProperties(
              width: const PagebuilderResponsiveOrConstant.constant(300.0),
              minLines: 1,
              maxLines: 1,
              isRequired: true,
              backgroundColor: null,
              borderColor: null,
              placeHolderTextProperties: PageBuilderTextProperties(
                  text: "test",
                  fontSize: const PagebuilderResponsiveOrConstant.constant(12.0),
                  fontFamily: "Poppins",
                  lineHeight: null,
                  letterSpacing: null,
                  textShadow: null,
                  color: null,
                  alignment: null),
              textProperties: PageBuilderTextProperties(
                  text: "test",
                  fontSize: const PagebuilderResponsiveOrConstant.constant(12.0),
                  fontFamily: "Poppins",
                  lineHeight: null,
                  letterSpacing: null,
                  textShadow: null,
                  color: null,
                  alignment: null)),
          buttonProperties: PageBuilderButtonProperties(
              width: const PagebuilderResponsiveOrConstant.constant(200),
              height: const PagebuilderResponsiveOrConstant.constant(100),
              border: const PagebuilderBorder(radius: 12.0, width: null, color: null),
              backgroundPaint: null,
              textProperties: null));
      final properties2 = PageBuilderContactFormProperties(
          email: "test@test.de",
          nameTextFieldProperties: PageBuilderTextFieldProperties(
              width: const PagebuilderResponsiveOrConstant.constant(200.0),
              minLines: 1,
              maxLines: 1,
              isRequired: true,
              backgroundColor: null,
              borderColor: null,
              placeHolderTextProperties: PageBuilderTextProperties(
                  text: "test",
                  fontSize: const PagebuilderResponsiveOrConstant.constant(12.0),
                  fontFamily: "Poppins",
                  lineHeight: null,
                  letterSpacing: null,
                  textShadow: null,
                  color: null,
                  alignment: null),
              textProperties: PageBuilderTextProperties(
                  text: "test",
                  fontSize: const PagebuilderResponsiveOrConstant.constant(12.0),
                  fontFamily: "Poppins",
                  lineHeight: null,
                  letterSpacing: null,
                  textShadow: null,
                  color: null,
                  alignment: null)),
          emailTextFieldProperties: PageBuilderTextFieldProperties(
              width: const PagebuilderResponsiveOrConstant.constant(300.0),
              minLines: 1,
              maxLines: 1,
              isRequired: true,
              backgroundColor: null,
              borderColor: null,
              placeHolderTextProperties: PageBuilderTextProperties(
                  text: "test",
                  fontSize: const PagebuilderResponsiveOrConstant.constant(12.0),
                  fontFamily: "Poppins",
                  lineHeight: null,
                  letterSpacing: null,
                  textShadow: null,
                  color: null,
                  alignment: null),
              textProperties: PageBuilderTextProperties(
                  text: "test",
                  fontSize: const PagebuilderResponsiveOrConstant.constant(12.0),
                  fontFamily: "Poppins",
                  lineHeight: null,
                  letterSpacing: null,
                  textShadow: null,
                  color: null,
                  alignment: null)),
          phoneTextFieldProperties: PageBuilderTextFieldProperties(
              width: const PagebuilderResponsiveOrConstant.constant(300.0),
              minLines: 1,
              maxLines: 1,
              isRequired: true,
              backgroundColor: null,
              borderColor: null,
              placeHolderTextProperties: PageBuilderTextProperties(
                  text: "test",
                  fontSize: const PagebuilderResponsiveOrConstant.constant(12.0),
                  fontFamily: "Poppins",
                  lineHeight: null,
                  letterSpacing: null,
                  textShadow: null,
                  color: null,
                  alignment: null),
              textProperties: PageBuilderTextProperties(
                  text: "test",
                  fontSize: const PagebuilderResponsiveOrConstant.constant(12.0),
                  fontFamily: "Poppins",
                  lineHeight: null,
                  letterSpacing: null,
                  textShadow: null,
                  color: null,
                  alignment: null)),
          messageTextFieldProperties: PageBuilderTextFieldProperties(
              width: const PagebuilderResponsiveOrConstant.constant(300.0),
              minLines: 1,
              maxLines: 1,
              isRequired: true,
              backgroundColor: null,
              borderColor: null,
              placeHolderTextProperties: PageBuilderTextProperties(
                  text: "test",
                  fontSize: const PagebuilderResponsiveOrConstant.constant(12.0),
                  fontFamily: "Poppins",
                  lineHeight: null,
                  letterSpacing: null,
                  textShadow: null,
                  color: null,
                  alignment: null),
              textProperties: PageBuilderTextProperties(
                  text: "test",
                  fontSize: const PagebuilderResponsiveOrConstant.constant(12.0),
                  fontFamily: "Poppins",
                  lineHeight: null,
                  letterSpacing: null,
                  textShadow: null,
                  color: null,
                  alignment: null)),
          buttonProperties: PageBuilderButtonProperties(
              width: const PagebuilderResponsiveOrConstant.constant(200),
              height: const PagebuilderResponsiveOrConstant.constant(100),
              border: const PagebuilderBorder(radius: 12.0, width: null, color: null),
              backgroundPaint: null,
              textProperties: null));
      // Then
      expect(properties1, properties2);
    });
  });
}
