// Mocks generated by Mockito 5.4.4 from annotations
// in finanzbegleiter/test/validators/auth_validator_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:finanzbegleiter/l10n/generated/app_localizations.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AppLocalizations].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppLocalizations extends _i1.Mock implements _i2.AppLocalizations {
  MockAppLocalizations() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get localeName => (super.noSuchMethod(
        Invocation.getter(#localeName),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#localeName),
        ),
      ) as String);

  @override
  String get register_title => (super.noSuchMethod(
        Invocation.getter(#register_title),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#register_title),
        ),
      ) as String);

  @override
  String get register_subtitle => (super.noSuchMethod(
        Invocation.getter(#register_subtitle),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#register_subtitle),
        ),
      ) as String);

  @override
  String get register_firstname => (super.noSuchMethod(
        Invocation.getter(#register_firstname),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#register_firstname),
        ),
      ) as String);

  @override
  String get register_lastname => (super.noSuchMethod(
        Invocation.getter(#register_lastname),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#register_lastname),
        ),
      ) as String);

  @override
  String get register_birthdate => (super.noSuchMethod(
        Invocation.getter(#register_birthdate),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#register_birthdate),
        ),
      ) as String);

  @override
  String get register_address => (super.noSuchMethod(
        Invocation.getter(#register_address),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#register_address),
        ),
      ) as String);

  @override
  String get register_postcode => (super.noSuchMethod(
        Invocation.getter(#register_postcode),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#register_postcode),
        ),
      ) as String);

  @override
  String get register_place => (super.noSuchMethod(
        Invocation.getter(#register_place),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#register_place),
        ),
      ) as String);

  @override
  String get register_email => (super.noSuchMethod(
        Invocation.getter(#register_email),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#register_email),
        ),
      ) as String);

  @override
  String get register_password => (super.noSuchMethod(
        Invocation.getter(#register_password),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#register_password),
        ),
      ) as String);

  @override
  String get register_repeat_password => (super.noSuchMethod(
        Invocation.getter(#register_repeat_password),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#register_repeat_password),
        ),
      ) as String);

  @override
  String get register_code => (super.noSuchMethod(
        Invocation.getter(#register_code),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#register_code),
        ),
      ) as String);

  @override
  String get register_now_buttontitle => (super.noSuchMethod(
        Invocation.getter(#register_now_buttontitle),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#register_now_buttontitle),
        ),
      ) as String);

  @override
  String get register_invalid_code_error => (super.noSuchMethod(
        Invocation.getter(#register_invalid_code_error),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#register_invalid_code_error),
        ),
      ) as String);

  @override
  String get login_title => (super.noSuchMethod(
        Invocation.getter(#login_title),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#login_title),
        ),
      ) as String);

  @override
  String get login_subtitle => (super.noSuchMethod(
        Invocation.getter(#login_subtitle),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#login_subtitle),
        ),
      ) as String);

  @override
  String get login_email => (super.noSuchMethod(
        Invocation.getter(#login_email),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#login_email),
        ),
      ) as String);

  @override
  String get login_password => (super.noSuchMethod(
        Invocation.getter(#login_password),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#login_password),
        ),
      ) as String);

  @override
  String get login_login_buttontitle => (super.noSuchMethod(
        Invocation.getter(#login_login_buttontitle),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#login_login_buttontitle),
        ),
      ) as String);

  @override
  String get delete_buttontitle => (super.noSuchMethod(
        Invocation.getter(#delete_buttontitle),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#delete_buttontitle),
        ),
      ) as String);

  @override
  String get cancel_buttontitle => (super.noSuchMethod(
        Invocation.getter(#cancel_buttontitle),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#cancel_buttontitle),
        ),
      ) as String);

  @override
  String get changes_save_button_title => (super.noSuchMethod(
        Invocation.getter(#changes_save_button_title),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#changes_save_button_title),
        ),
      ) as String);

  @override
  String get login_password_forgotten_text => (super.noSuchMethod(
        Invocation.getter(#login_password_forgotten_text),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#login_password_forgotten_text),
        ),
      ) as String);

  @override
  String get login_password_forgotten_linktext => (super.noSuchMethod(
        Invocation.getter(#login_password_forgotten_linktext),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#login_password_forgotten_linktext),
        ),
      ) as String);

  @override
  String get login_register_linktitle => (super.noSuchMethod(
        Invocation.getter(#login_register_linktitle),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#login_register_linktitle),
        ),
      ) as String);

  @override
  String get login_register_text => (super.noSuchMethod(
        Invocation.getter(#login_register_text),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#login_register_text),
        ),
      ) as String);

  @override
  String get auth_validation_missing_email => (super.noSuchMethod(
        Invocation.getter(#auth_validation_missing_email),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#auth_validation_missing_email),
        ),
      ) as String);

  @override
  String get auth_validation_invalid_email => (super.noSuchMethod(
        Invocation.getter(#auth_validation_invalid_email),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#auth_validation_invalid_email),
        ),
      ) as String);

  @override
  String get auth_validation_missing_password => (super.noSuchMethod(
        Invocation.getter(#auth_validation_missing_password),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#auth_validation_missing_password),
        ),
      ) as String);

  @override
  String get auth_validation_confirm_password => (super.noSuchMethod(
        Invocation.getter(#auth_validation_confirm_password),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#auth_validation_confirm_password),
        ),
      ) as String);

  @override
  String get auth_validation_matching_passwords => (super.noSuchMethod(
        Invocation.getter(#auth_validation_matching_passwords),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#auth_validation_matching_passwords),
        ),
      ) as String);

  @override
  String get auth_validation_missing_firstname => (super.noSuchMethod(
        Invocation.getter(#auth_validation_missing_firstname),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#auth_validation_missing_firstname),
        ),
      ) as String);

  @override
  String get auth_validation_long_firstname => (super.noSuchMethod(
        Invocation.getter(#auth_validation_long_firstname),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#auth_validation_long_firstname),
        ),
      ) as String);

  @override
  String get auth_validation_missing_lastname => (super.noSuchMethod(
        Invocation.getter(#auth_validation_missing_lastname),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#auth_validation_missing_lastname),
        ),
      ) as String);

  @override
  String get auth_validation_long_lastname => (super.noSuchMethod(
        Invocation.getter(#auth_validation_long_lastname),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#auth_validation_long_lastname),
        ),
      ) as String);

  @override
  String get auth_validation_missing_birthdate => (super.noSuchMethod(
        Invocation.getter(#auth_validation_missing_birthdate),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#auth_validation_missing_birthdate),
        ),
      ) as String);

  @override
  String get auth_validation_invalid_birthdate => (super.noSuchMethod(
        Invocation.getter(#auth_validation_invalid_birthdate),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#auth_validation_invalid_birthdate),
        ),
      ) as String);

  @override
  String get auth_validation_invalid_date => (super.noSuchMethod(
        Invocation.getter(#auth_validation_invalid_date),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#auth_validation_invalid_date),
        ),
      ) as String);

  @override
  String get auth_validation_invalid_postcode => (super.noSuchMethod(
        Invocation.getter(#auth_validation_invalid_postcode),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#auth_validation_invalid_postcode),
        ),
      ) as String);

  @override
  String get auth_validation_missing_code => (super.noSuchMethod(
        Invocation.getter(#auth_validation_missing_code),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#auth_validation_missing_code),
        ),
      ) as String);

  @override
  String get auth_validation_missing_gender => (super.noSuchMethod(
        Invocation.getter(#auth_validation_missing_gender),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#auth_validation_missing_gender),
        ),
      ) as String);

  @override
  String get auth_validation_missing_additional_info => (super.noSuchMethod(
        Invocation.getter(#auth_validation_missing_additional_info),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#auth_validation_missing_additional_info),
        ),
      ) as String);

  @override
  String get auth_validation_additional_info_exceed_limit =>
      (super.noSuchMethod(
        Invocation.getter(#auth_validation_additional_info_exceed_limit),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#auth_validation_additional_info_exceed_limit),
        ),
      ) as String);

  @override
  String get menuitems_profile => (super.noSuchMethod(
        Invocation.getter(#menuitems_profile),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#menuitems_profile),
        ),
      ) as String);

  @override
  String get menuitems_dashboard => (super.noSuchMethod(
        Invocation.getter(#menuitems_dashboard),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#menuitems_dashboard),
        ),
      ) as String);

  @override
  String get menuitems_recommendations => (super.noSuchMethod(
        Invocation.getter(#menuitems_recommendations),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#menuitems_recommendations),
        ),
      ) as String);

  @override
  String get menuitems_promoters => (super.noSuchMethod(
        Invocation.getter(#menuitems_promoters),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#menuitems_promoters),
        ),
      ) as String);

  @override
  String get landingpage_overview_title => (super.noSuchMethod(
        Invocation.getter(#landingpage_overview_title),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#landingpage_overview_title),
        ),
      ) as String);

  @override
  String get menuitems_landingpage => (super.noSuchMethod(
        Invocation.getter(#menuitems_landingpage),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#menuitems_landingpage),
        ),
      ) as String);

  @override
  String get menuitems_company_requests => (super.noSuchMethod(
        Invocation.getter(#menuitems_company_requests),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#menuitems_company_requests),
        ),
      ) as String);

  @override
  String get landingpage_overview_error_view_title => (super.noSuchMethod(
        Invocation.getter(#landingpage_overview_error_view_title),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#landingpage_overview_error_view_title),
        ),
      ) as String);

  @override
  String get landingpage_overview_empty_page_title => (super.noSuchMethod(
        Invocation.getter(#landingpage_overview_empty_page_title),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#landingpage_overview_empty_page_title),
        ),
      ) as String);

  @override
  String get landingpage_overview_empty_page_subtitle => (super.noSuchMethod(
        Invocation.getter(#landingpage_overview_empty_page_subtitle),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#landingpage_overview_empty_page_subtitle),
        ),
      ) as String);

  @override
  String get landingpage_overview_empty_page_button_title =>
      (super.noSuchMethod(
        Invocation.getter(#landingpage_overview_empty_page_button_title),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#landingpage_overview_empty_page_button_title),
        ),
      ) as String);

  @override
  String get landingpage_delete_alert_title => (super.noSuchMethod(
        Invocation.getter(#landingpage_delete_alert_title),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#landingpage_delete_alert_title),
        ),
      ) as String);

  @override
  String get landingpage_delete_alert_msg => (super.noSuchMethod(
        Invocation.getter(#landingpage_delete_alert_msg),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#landingpage_delete_alert_msg),
        ),
      ) as String);

  @override
  String get landingpage_success_delete_snackbar_message => (super.noSuchMethod(
        Invocation.getter(#landingpage_success_delete_snackbar_message),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#landingpage_success_delete_snackbar_message),
        ),
      ) as String);

  @override
  String get landingpage_snackbar_success => (super.noSuchMethod(
        Invocation.getter(#landingpage_snackbar_success),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#landingpage_snackbar_success),
        ),
      ) as String);

  @override
  String get landingpage_snackbar_success_changed => (super.noSuchMethod(
        Invocation.getter(#landingpage_snackbar_success_changed),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#landingpage_snackbar_success_changed),
        ),
      ) as String);

  @override
  String get landingpage_snackbar_success_duplicated => (super.noSuchMethod(
        Invocation.getter(#landingpage_snackbar_success_duplicated),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#landingpage_snackbar_success_duplicated),
        ),
      ) as String);

  @override
  String get landingpage_overview_max_count_msg => (super.noSuchMethod(
        Invocation.getter(#landingpage_overview_max_count_msg),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#landingpage_overview_max_count_msg),
        ),
      ) as String);

  @override
  String get landingpage_create_buttontitle => (super.noSuchMethod(
        Invocation.getter(#landingpage_create_buttontitle),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#landingpage_create_buttontitle),
        ),
      ) as String);

  @override
  String get landingpage_validate_LandingPageName => (super.noSuchMethod(
        Invocation.getter(#landingpage_validate_LandingPageName),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#landingpage_validate_LandingPageName),
        ),
      ) as String);

  @override
  String get landingpage_validate_LandingPageText => (super.noSuchMethod(
        Invocation.getter(#landingpage_validate_LandingPageText),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#landingpage_validate_LandingPageText),
        ),
      ) as String);

  @override
  String get landingpage_create_txt => (super.noSuchMethod(
        Invocation.getter(#landingpage_create_txt),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#landingpage_create_txt),
        ),
      ) as String);

  @override
  String get landingpage_create_promotion_template_description =>
      (super.noSuchMethod(
        Invocation.getter(#landingpage_create_promotion_template_description),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#landingpage_create_promotion_template_description),
        ),
      ) as String);

  @override
  String get landingpage_create_promotion_template_placeholder =>
      (super.noSuchMethod(
        Invocation.getter(#landingpage_create_promotion_template_placeholder),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#landingpage_create_promotion_template_placeholder),
        ),
      ) as String);

  @override
  String get landingpage_create_promotion_template_default_text =>
      (super.noSuchMethod(
        Invocation.getter(#landingpage_create_promotion_template_default_text),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(
              #landingpage_create_promotion_template_default_text),
        ),
      ) as String);

  @override
  String get emoji_search_placeholder => (super.noSuchMethod(
        Invocation.getter(#emoji_search_placeholder),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#emoji_search_placeholder),
        ),
      ) as String);

  @override
  String get open_emoji_picker_tooltip => (super.noSuchMethod(
        Invocation.getter(#open_emoji_picker_tooltip),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#open_emoji_picker_tooltip),
        ),
      ) as String);

  @override
  String get landingpage_overview_context_menu_delete => (super.noSuchMethod(
        Invocation.getter(#landingpage_overview_context_menu_delete),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#landingpage_overview_context_menu_delete),
        ),
      ) as String);

  @override
  String get landingpage_overview_context_menu_duplicate => (super.noSuchMethod(
        Invocation.getter(#landingpage_overview_context_menu_duplicate),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#landingpage_overview_context_menu_duplicate),
        ),
      ) as String);

  @override
  String get placeholder_title => (super.noSuchMethod(
        Invocation.getter(#placeholder_title),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#placeholder_title),
        ),
      ) as String);

  @override
  String get placeholder_description => (super.noSuchMethod(
        Invocation.getter(#placeholder_description),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#placeholder_description),
        ),
      ) as String);

  @override
  String get error_msg_pleace_upload_picture => (super.noSuchMethod(
        Invocation.getter(#error_msg_pleace_upload_picture),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#error_msg_pleace_upload_picture),
        ),
      ) as String);

  @override
  String get menuitems_activities => (super.noSuchMethod(
        Invocation.getter(#menuitems_activities),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#menuitems_activities),
        ),
      ) as String);

  @override
  String get auth_failure_email_already_in_use => (super.noSuchMethod(
        Invocation.getter(#auth_failure_email_already_in_use),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#auth_failure_email_already_in_use),
        ),
      ) as String);

  @override
  String get auth_failure_invalid_email => (super.noSuchMethod(
        Invocation.getter(#auth_failure_invalid_email),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#auth_failure_invalid_email),
        ),
      ) as String);

  @override
  String get auth_failure_weak_password => (super.noSuchMethod(
        Invocation.getter(#auth_failure_weak_password),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#auth_failure_weak_password),
        ),
      ) as String);

  @override
  String get auth_failure_user_disabled => (super.noSuchMethod(
        Invocation.getter(#auth_failure_user_disabled),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#auth_failure_user_disabled),
        ),
      ) as String);

  @override
  String get auth_failure_user_not_found => (super.noSuchMethod(
        Invocation.getter(#auth_failure_user_not_found),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#auth_failure_user_not_found),
        ),
      ) as String);

  @override
  String get auth_failure_wrong_password => (super.noSuchMethod(
        Invocation.getter(#auth_failure_wrong_password),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#auth_failure_wrong_password),
        ),
      ) as String);

  @override
  String get auth_failure_invalid_credentials => (super.noSuchMethod(
        Invocation.getter(#auth_failure_invalid_credentials),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#auth_failure_invalid_credentials),
        ),
      ) as String);

  @override
  String get auth_failure_too_many_requests => (super.noSuchMethod(
        Invocation.getter(#auth_failure_too_many_requests),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#auth_failure_too_many_requests),
        ),
      ) as String);

  @override
  String get auth_failure_user_mismatch => (super.noSuchMethod(
        Invocation.getter(#auth_failure_user_mismatch),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#auth_failure_user_mismatch),
        ),
      ) as String);

  @override
  String get auth_failure_invalid_verification_code => (super.noSuchMethod(
        Invocation.getter(#auth_failure_invalid_verification_code),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#auth_failure_invalid_verification_code),
        ),
      ) as String);

  @override
  String get auth_failure_invalid_verification_id => (super.noSuchMethod(
        Invocation.getter(#auth_failure_invalid_verification_id),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#auth_failure_invalid_verification_id),
        ),
      ) as String);

  @override
  String get auth_failure_requires_recent_login => (super.noSuchMethod(
        Invocation.getter(#auth_failure_requires_recent_login),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#auth_failure_requires_recent_login),
        ),
      ) as String);

  @override
  String get auth_failure_missing_password => (super.noSuchMethod(
        Invocation.getter(#auth_failure_missing_password),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#auth_failure_missing_password),
        ),
      ) as String);

  @override
  String get auth_failure_unknown => (super.noSuchMethod(
        Invocation.getter(#auth_failure_unknown),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#auth_failure_unknown),
        ),
      ) as String);

  @override
  String get database_failure_permission_denied => (super.noSuchMethod(
        Invocation.getter(#database_failure_permission_denied),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#database_failure_permission_denied),
        ),
      ) as String);

  @override
  String get database_failure_not_found => (super.noSuchMethod(
        Invocation.getter(#database_failure_not_found),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#database_failure_not_found),
        ),
      ) as String);

  @override
  String get database_failure_already_exists => (super.noSuchMethod(
        Invocation.getter(#database_failure_already_exists),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#database_failure_already_exists),
        ),
      ) as String);

  @override
  String get database_failure_deadline_exceeded => (super.noSuchMethod(
        Invocation.getter(#database_failure_deadline_exceeded),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#database_failure_deadline_exceeded),
        ),
      ) as String);

  @override
  String get database_failure_cancelled => (super.noSuchMethod(
        Invocation.getter(#database_failure_cancelled),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#database_failure_cancelled),
        ),
      ) as String);

  @override
  String get database_failure_unavailable => (super.noSuchMethod(
        Invocation.getter(#database_failure_unavailable),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#database_failure_unavailable),
        ),
      ) as String);

  @override
  String get database_failure_unknown => (super.noSuchMethod(
        Invocation.getter(#database_failure_unknown),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#database_failure_unknown),
        ),
      ) as String);

  @override
  String get storage_failure_object_not_found => (super.noSuchMethod(
        Invocation.getter(#storage_failure_object_not_found),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#storage_failure_object_not_found),
        ),
      ) as String);

  @override
  String get storage_failure_not_authenticated => (super.noSuchMethod(
        Invocation.getter(#storage_failure_not_authenticated),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#storage_failure_not_authenticated),
        ),
      ) as String);

  @override
  String get storage_failure_not_authorized => (super.noSuchMethod(
        Invocation.getter(#storage_failure_not_authorized),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#storage_failure_not_authorized),
        ),
      ) as String);

  @override
  String get storage_failure_retry_limit_exceeded => (super.noSuchMethod(
        Invocation.getter(#storage_failure_retry_limit_exceeded),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#storage_failure_retry_limit_exceeded),
        ),
      ) as String);

  @override
  String get storage_failure_unknown => (super.noSuchMethod(
        Invocation.getter(#storage_failure_unknown),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#storage_failure_unknown),
        ),
      ) as String);

  @override
  String get password_forgotten_title => (super.noSuchMethod(
        Invocation.getter(#password_forgotten_title),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#password_forgotten_title),
        ),
      ) as String);

  @override
  String get password_forgotten_description => (super.noSuchMethod(
        Invocation.getter(#password_forgotten_description),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#password_forgotten_description),
        ),
      ) as String);

  @override
  String get password_forgotten_success_dialog_title => (super.noSuchMethod(
        Invocation.getter(#password_forgotten_success_dialog_title),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#password_forgotten_success_dialog_title),
        ),
      ) as String);

  @override
  String get password_forgotten_success_dialog_description =>
      (super.noSuchMethod(
        Invocation.getter(#password_forgotten_success_dialog_description),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#password_forgotten_success_dialog_description),
        ),
      ) as String);

  @override
  String get password_forgotten_success_dialog_ok_button_title =>
      (super.noSuchMethod(
        Invocation.getter(#password_forgotten_success_dialog_ok_button_title),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#password_forgotten_success_dialog_ok_button_title),
        ),
      ) as String);

  @override
  String get password_forgotten_button_title => (super.noSuchMethod(
        Invocation.getter(#password_forgotten_button_title),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#password_forgotten_button_title),
        ),
      ) as String);

  @override
  String get password_forgotten_email_textfield_placeholder =>
      (super.noSuchMethod(
        Invocation.getter(#password_forgotten_email_textfield_placeholder),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#password_forgotten_email_textfield_placeholder),
        ),
      ) as String);

  @override
  String get general_error_view_refresh_button_title => (super.noSuchMethod(
        Invocation.getter(#general_error_view_refresh_button_title),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#general_error_view_refresh_button_title),
        ),
      ) as String);

  @override
  String get profile_page_email_section_email => (super.noSuchMethod(
        Invocation.getter(#profile_page_email_section_email),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#profile_page_email_section_email),
        ),
      ) as String);

  @override
  String get profile_page_email_section_status => (super.noSuchMethod(
        Invocation.getter(#profile_page_email_section_status),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#profile_page_email_section_status),
        ),
      ) as String);

  @override
  String get profile_page_email_section_description => (super.noSuchMethod(
        Invocation.getter(#profile_page_email_section_description),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#profile_page_email_section_description),
        ),
      ) as String);

  @override
  String get profile_page_email_section_change_email_button_title =>
      (super.noSuchMethod(
        Invocation.getter(
            #profile_page_email_section_change_email_button_title),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(
              #profile_page_email_section_change_email_button_title),
        ),
      ) as String);

  @override
  String get profile_page_email_section_change_email_password_description =>
      (super.noSuchMethod(
        Invocation.getter(
            #profile_page_email_section_change_email_password_description),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(
              #profile_page_email_section_change_email_password_description),
        ),
      ) as String);

  @override
  String
      get profile_page_email_section_change_email_password_continue_button_title =>
          (super.noSuchMethod(
            Invocation.getter(
                #profile_page_email_section_change_email_password_continue_button_title),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(
                  #profile_page_email_section_change_email_password_continue_button_title),
            ),
          ) as String);

  @override
  String get profile_page_email_section_resend_verify_email_button_title =>
      (super.noSuchMethod(
        Invocation.getter(
            #profile_page_email_section_resend_verify_email_button_title),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(
              #profile_page_email_section_resend_verify_email_button_title),
        ),
      ) as String);

  @override
  String get profile_page_email_section_title => (super.noSuchMethod(
        Invocation.getter(#profile_page_email_section_title),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#profile_page_email_section_title),
        ),
      ) as String);

  @override
  String get profile_page_email_section_verification_badge_verified =>
      (super.noSuchMethod(
        Invocation.getter(
            #profile_page_email_section_verification_badge_verified),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(
              #profile_page_email_section_verification_badge_verified),
        ),
      ) as String);

  @override
  String get profile_page_email_section_verification_badge_unverified =>
      (super.noSuchMethod(
        Invocation.getter(
            #profile_page_email_section_verification_badge_unverified),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(
              #profile_page_email_section_verification_badge_unverified),
        ),
      ) as String);

  @override
  String get profile_page_image_section_validation_exceededFileSize =>
      (super.noSuchMethod(
        Invocation.getter(
            #profile_page_image_section_validation_exceededFileSize),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(
              #profile_page_image_section_validation_exceededFileSize),
        ),
      ) as String);

  @override
  String get profile_page_image_section_validation_not_valid =>
      (super.noSuchMethod(
        Invocation.getter(#profile_page_image_section_validation_not_valid),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#profile_page_image_section_validation_not_valid),
        ),
      ) as String);

  @override
  String get profile_page_image_section_only_one_allowed => (super.noSuchMethod(
        Invocation.getter(#profile_page_image_section_only_one_allowed),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#profile_page_image_section_only_one_allowed),
        ),
      ) as String);

  @override
  String get profile_page_image_section_upload_not_found => (super.noSuchMethod(
        Invocation.getter(#profile_page_image_section_upload_not_found),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#profile_page_image_section_upload_not_found),
        ),
      ) as String);

  @override
  String
      get profile_page_image_section_large_image_view_close_button_tooltip_title =>
          (super.noSuchMethod(
            Invocation.getter(
                #profile_page_image_section_large_image_view_close_button_tooltip_title),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(
                  #profile_page_image_section_large_image_view_close_button_tooltip_title),
            ),
          ) as String);

  @override
  String get profile_page_password_update_section_title => (super.noSuchMethod(
        Invocation.getter(#profile_page_password_update_section_title),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#profile_page_password_update_section_title),
        ),
      ) as String);

  @override
  String get profile_page_password_update_section_new_password_description =>
      (super.noSuchMethod(
        Invocation.getter(
            #profile_page_password_update_section_new_password_description),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(
              #profile_page_password_update_section_new_password_description),
        ),
      ) as String);

  @override
  String
      get profile_page_password_update_section_new_password_textfield_placeholder =>
          (super.noSuchMethod(
            Invocation.getter(
                #profile_page_password_update_section_new_password_textfield_placeholder),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(
                  #profile_page_password_update_section_new_password_textfield_placeholder),
            ),
          ) as String);

  @override
  String
      get profile_page_password_update_section_new_password_repeat_textfield_placeholder =>
          (super.noSuchMethod(
            Invocation.getter(
                #profile_page_password_update_section_new_password_repeat_textfield_placeholder),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(
                  #profile_page_password_update_section_new_password_repeat_textfield_placeholder),
            ),
          ) as String);

  @override
  String
      get profile_page_password_update_section_new_password_confirm_button_text =>
          (super.noSuchMethod(
            Invocation.getter(
                #profile_page_password_update_section_new_password_confirm_button_text),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(
                  #profile_page_password_update_section_new_password_confirm_button_text),
            ),
          ) as String);

  @override
  String get profile_page_password_update_section_reauth_description =>
      (super.noSuchMethod(
        Invocation.getter(
            #profile_page_password_update_section_reauth_description),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(
              #profile_page_password_update_section_reauth_description),
        ),
      ) as String);

  @override
  String
      get profile_page_password_update_section_reauth_password_textfield_placeholder =>
          (super.noSuchMethod(
            Invocation.getter(
                #profile_page_password_update_section_reauth_password_textfield_placeholder),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(
                  #profile_page_password_update_section_reauth_password_textfield_placeholder),
            ),
          ) as String);

  @override
  String
      get profile_page_password_update_section_reauth_continue_button_title =>
          (super.noSuchMethod(
            Invocation.getter(
                #profile_page_password_update_section_reauth_continue_button_title),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(
                  #profile_page_password_update_section_reauth_continue_button_title),
            ),
          ) as String);

  @override
  String get profile_page_contact_section_title => (super.noSuchMethod(
        Invocation.getter(#profile_page_contact_section_title),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#profile_page_contact_section_title),
        ),
      ) as String);

  @override
  String get profile_page_contact_section_form_firstname => (super.noSuchMethod(
        Invocation.getter(#profile_page_contact_section_form_firstname),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#profile_page_contact_section_form_firstname),
        ),
      ) as String);

  @override
  String get profile_page_contact_section_form_lastname => (super.noSuchMethod(
        Invocation.getter(#profile_page_contact_section_form_lastname),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#profile_page_contact_section_form_lastname),
        ),
      ) as String);

  @override
  String get profile_page_contact_section_form_address => (super.noSuchMethod(
        Invocation.getter(#profile_page_contact_section_form_address),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#profile_page_contact_section_form_address),
        ),
      ) as String);

  @override
  String get profile_page_contact_section_form_postcode => (super.noSuchMethod(
        Invocation.getter(#profile_page_contact_section_form_postcode),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#profile_page_contact_section_form_postcode),
        ),
      ) as String);

  @override
  String get profile_page_contact_section_form_place => (super.noSuchMethod(
        Invocation.getter(#profile_page_contact_section_form_place),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#profile_page_contact_section_form_place),
        ),
      ) as String);

  @override
  String get profile_page_contact_section_form_save_button_title =>
      (super.noSuchMethod(
        Invocation.getter(#profile_page_contact_section_form_save_button_title),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(
              #profile_page_contact_section_form_save_button_title),
        ),
      ) as String);

  @override
  String get profile_page_snackbar_image_changed_message => (super.noSuchMethod(
        Invocation.getter(#profile_page_snackbar_image_changed_message),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#profile_page_snackbar_image_changed_message),
        ),
      ) as String);

  @override
  String get profile_page_snackbar_contact_information_changes =>
      (super.noSuchMethod(
        Invocation.getter(#profile_page_snackbar_contact_information_changes),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#profile_page_snackbar_contact_information_changes),
        ),
      ) as String);

  @override
  String get profile_page_snackbar_email_verification => (super.noSuchMethod(
        Invocation.getter(#profile_page_snackbar_email_verification),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#profile_page_snackbar_email_verification),
        ),
      ) as String);

  @override
  String get profile_page_snackbar_company_registered => (super.noSuchMethod(
        Invocation.getter(#profile_page_snackbar_company_registered),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#profile_page_snackbar_company_registered),
        ),
      ) as String);

  @override
  String get profile_page_logout_button_title => (super.noSuchMethod(
        Invocation.getter(#profile_page_logout_button_title),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#profile_page_logout_button_title),
        ),
      ) as String);

  @override
  String get profile_page_request_failure_message => (super.noSuchMethod(
        Invocation.getter(#profile_page_request_failure_message),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#profile_page_request_failure_message),
        ),
      ) as String);

  @override
  String get profile_page_promoters_section_title => (super.noSuchMethod(
        Invocation.getter(#profile_page_promoters_section_title),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#profile_page_promoters_section_title),
        ),
      ) as String);

  @override
  String get profile_page_promoters_section_recommender_count =>
      (super.noSuchMethod(
        Invocation.getter(#profile_page_promoters_section_recommender_count),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#profile_page_promoters_section_recommender_count),
        ),
      ) as String);

  @override
  String get gender_picker_choose => (super.noSuchMethod(
        Invocation.getter(#gender_picker_choose),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#gender_picker_choose),
        ),
      ) as String);

  @override
  String get gender_picker_not_choosen => (super.noSuchMethod(
        Invocation.getter(#gender_picker_not_choosen),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#gender_picker_not_choosen),
        ),
      ) as String);

  @override
  String get gender_picker_male => (super.noSuchMethod(
        Invocation.getter(#gender_picker_male),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#gender_picker_male),
        ),
      ) as String);

  @override
  String get gender_picker_female => (super.noSuchMethod(
        Invocation.getter(#gender_picker_female),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#gender_picker_female),
        ),
      ) as String);

  @override
  String get register_promoter_email_already_in_use => (super.noSuchMethod(
        Invocation.getter(#register_promoter_email_already_in_use),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#register_promoter_email_already_in_use),
        ),
      ) as String);

  @override
  String get register_promoter_title => (super.noSuchMethod(
        Invocation.getter(#register_promoter_title),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#register_promoter_title),
        ),
      ) as String);

  @override
  String get register_promoter_first_name => (super.noSuchMethod(
        Invocation.getter(#register_promoter_first_name),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#register_promoter_first_name),
        ),
      ) as String);

  @override
  String get register_promoter_last_name => (super.noSuchMethod(
        Invocation.getter(#register_promoter_last_name),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#register_promoter_last_name),
        ),
      ) as String);

  @override
  String get register_promoter_birthdate => (super.noSuchMethod(
        Invocation.getter(#register_promoter_birthdate),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#register_promoter_birthdate),
        ),
      ) as String);

  @override
  String get register_promoter_email => (super.noSuchMethod(
        Invocation.getter(#register_promoter_email),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#register_promoter_email),
        ),
      ) as String);

  @override
  String get register_promoter_additional_info => (super.noSuchMethod(
        Invocation.getter(#register_promoter_additional_info),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#register_promoter_additional_info),
        ),
      ) as String);

  @override
  String get register_promoter_register_button => (super.noSuchMethod(
        Invocation.getter(#register_promoter_register_button),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#register_promoter_register_button),
        ),
      ) as String);

  @override
  String get register_promoter_snackbar_success => (super.noSuchMethod(
        Invocation.getter(#register_promoter_snackbar_success),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#register_promoter_snackbar_success),
        ),
      ) as String);

  @override
  String get register_promoter_no_landingpage_title => (super.noSuchMethod(
        Invocation.getter(#register_promoter_no_landingpage_title),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#register_promoter_no_landingpage_title),
        ),
      ) as String);

  @override
  String get register_promoter_no_landingpage_subtitle => (super.noSuchMethod(
        Invocation.getter(#register_promoter_no_landingpage_subtitle),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#register_promoter_no_landingpage_subtitle),
        ),
      ) as String);

  @override
  String get register_promoter_missing_landingpage_error_message =>
      (super.noSuchMethod(
        Invocation.getter(#register_promoter_missing_landingpage_error_message),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(
              #register_promoter_missing_landingpage_error_message),
        ),
      ) as String);

  @override
  String get register_promoter_missing_company_error_message =>
      (super.noSuchMethod(
        Invocation.getter(#register_promoter_missing_company_error_message),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#register_promoter_missing_company_error_message),
        ),
      ) as String);

  @override
  String get promoter_overview_title => (super.noSuchMethod(
        Invocation.getter(#promoter_overview_title),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#promoter_overview_title),
        ),
      ) as String);

  @override
  String get promoter_overview_search_placeholder => (super.noSuchMethod(
        Invocation.getter(#promoter_overview_search_placeholder),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#promoter_overview_search_placeholder),
        ),
      ) as String);

  @override
  String get promoter_overview_filter_show_all => (super.noSuchMethod(
        Invocation.getter(#promoter_overview_filter_show_all),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#promoter_overview_filter_show_all),
        ),
      ) as String);

  @override
  String get promoter_overview_filter_show_registered => (super.noSuchMethod(
        Invocation.getter(#promoter_overview_filter_show_registered),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#promoter_overview_filter_show_registered),
        ),
      ) as String);

  @override
  String get promoter_overview_filter_show_unregistered => (super.noSuchMethod(
        Invocation.getter(#promoter_overview_filter_show_unregistered),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#promoter_overview_filter_show_unregistered),
        ),
      ) as String);

  @override
  String get promoter_overview_filter_sortby_choose => (super.noSuchMethod(
        Invocation.getter(#promoter_overview_filter_sortby_choose),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#promoter_overview_filter_sortby_choose),
        ),
      ) as String);

  @override
  String get promoter_overview_filter_sortby_date => (super.noSuchMethod(
        Invocation.getter(#promoter_overview_filter_sortby_date),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#promoter_overview_filter_sortby_date),
        ),
      ) as String);

  @override
  String get promoter_overview_filter_sortby_firstname => (super.noSuchMethod(
        Invocation.getter(#promoter_overview_filter_sortby_firstname),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#promoter_overview_filter_sortby_firstname),
        ),
      ) as String);

  @override
  String get promoter_overview_filter_sortby_lastname => (super.noSuchMethod(
        Invocation.getter(#promoter_overview_filter_sortby_lastname),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#promoter_overview_filter_sortby_lastname),
        ),
      ) as String);

  @override
  String get promoter_overview_filter_sortby_email => (super.noSuchMethod(
        Invocation.getter(#promoter_overview_filter_sortby_email),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#promoter_overview_filter_sortby_email),
        ),
      ) as String);

  @override
  String get promoter_overview_filter_sortorder_asc => (super.noSuchMethod(
        Invocation.getter(#promoter_overview_filter_sortorder_asc),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#promoter_overview_filter_sortorder_asc),
        ),
      ) as String);

  @override
  String get promoter_overview_filter_sortorder_desc => (super.noSuchMethod(
        Invocation.getter(#promoter_overview_filter_sortorder_desc),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#promoter_overview_filter_sortorder_desc),
        ),
      ) as String);

  @override
  String get promoter_overview_no_search_results_title => (super.noSuchMethod(
        Invocation.getter(#promoter_overview_no_search_results_title),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#promoter_overview_no_search_results_title),
        ),
      ) as String);

  @override
  String get promoter_overview_no_search_results_subtitle =>
      (super.noSuchMethod(
        Invocation.getter(#promoter_overview_no_search_results_subtitle),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#promoter_overview_no_search_results_subtitle),
        ),
      ) as String);

  @override
  String get promoter_overview_registration_badge_registered =>
      (super.noSuchMethod(
        Invocation.getter(#promoter_overview_registration_badge_registered),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#promoter_overview_registration_badge_registered),
        ),
      ) as String);

  @override
  String get promoter_overview_registration_badge_unregistered =>
      (super.noSuchMethod(
        Invocation.getter(#promoter_overview_registration_badge_unregistered),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#promoter_overview_registration_badge_unregistered),
        ),
      ) as String);

  @override
  String get promoter_overview_empty_page_title => (super.noSuchMethod(
        Invocation.getter(#promoter_overview_empty_page_title),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#promoter_overview_empty_page_title),
        ),
      ) as String);

  @override
  String get promoter_overview_empty_page_subtitle => (super.noSuchMethod(
        Invocation.getter(#promoter_overview_empty_page_subtitle),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#promoter_overview_empty_page_subtitle),
        ),
      ) as String);

  @override
  String get promoter_overview_empty_page_button_title => (super.noSuchMethod(
        Invocation.getter(#promoter_overview_empty_page_button_title),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#promoter_overview_empty_page_button_title),
        ),
      ) as String);

  @override
  String get promoter_overview_error_view_title => (super.noSuchMethod(
        Invocation.getter(#promoter_overview_error_view_title),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#promoter_overview_error_view_title),
        ),
      ) as String);

  @override
  String get delete_account_title => (super.noSuchMethod(
        Invocation.getter(#delete_account_title),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#delete_account_title),
        ),
      ) as String);

  @override
  String get delete_account_subtitle => (super.noSuchMethod(
        Invocation.getter(#delete_account_subtitle),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#delete_account_subtitle),
        ),
      ) as String);

  @override
  String get delete_account_password_placeholder => (super.noSuchMethod(
        Invocation.getter(#delete_account_password_placeholder),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#delete_account_password_placeholder),
        ),
      ) as String);

  @override
  String get delete_account_button_title => (super.noSuchMethod(
        Invocation.getter(#delete_account_button_title),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#delete_account_button_title),
        ),
      ) as String);

  @override
  String get delete_account_confirmation_alert_title => (super.noSuchMethod(
        Invocation.getter(#delete_account_confirmation_alert_title),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#delete_account_confirmation_alert_title),
        ),
      ) as String);

  @override
  String get delete_account_confirmation_alert_message => (super.noSuchMethod(
        Invocation.getter(#delete_account_confirmation_alert_message),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#delete_account_confirmation_alert_message),
        ),
      ) as String);

  @override
  String get delete_account_confirmation_alert_ok_button_title =>
      (super.noSuchMethod(
        Invocation.getter(#delete_account_confirmation_alert_ok_button_title),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#delete_account_confirmation_alert_ok_button_title),
        ),
      ) as String);

  @override
  String get delete_account_confirmation_alert_cancel_button_title =>
      (super.noSuchMethod(
        Invocation.getter(
            #delete_account_confirmation_alert_cancel_button_title),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(
              #delete_account_confirmation_alert_cancel_button_title),
        ),
      ) as String);

  @override
  String get recommendations_choose_reason_placeholder => (super.noSuchMethod(
        Invocation.getter(#recommendations_choose_reason_placeholder),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#recommendations_choose_reason_placeholder),
        ),
      ) as String);

  @override
  String get recommendations_choose_reason_not_chosen => (super.noSuchMethod(
        Invocation.getter(#recommendations_choose_reason_not_chosen),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#recommendations_choose_reason_not_chosen),
        ),
      ) as String);

  @override
  String get recommendations_title => (super.noSuchMethod(
        Invocation.getter(#recommendations_title),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#recommendations_title),
        ),
      ) as String);

  @override
  String get recommendations_form_promoter_placeholder => (super.noSuchMethod(
        Invocation.getter(#recommendations_form_promoter_placeholder),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#recommendations_form_promoter_placeholder),
        ),
      ) as String);

  @override
  String get recommendations_form_service_provider_placeholder =>
      (super.noSuchMethod(
        Invocation.getter(#recommendations_form_service_provider_placeholder),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#recommendations_form_service_provider_placeholder),
        ),
      ) as String);

  @override
  String get recommendations_form_recommendation_name_placeholder =>
      (super.noSuchMethod(
        Invocation.getter(
            #recommendations_form_recommendation_name_placeholder),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(
              #recommendations_form_recommendation_name_placeholder),
        ),
      ) as String);

  @override
  String get recommendations_form_generate_recommendation_button_title =>
      (super.noSuchMethod(
        Invocation.getter(
            #recommendations_form_generate_recommendation_button_title),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(
              #recommendations_form_generate_recommendation_button_title),
        ),
      ) as String);

  @override
  String get recommendations_error_view_title => (super.noSuchMethod(
        Invocation.getter(#recommendations_error_view_title),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#recommendations_error_view_title),
        ),
      ) as String);

  @override
  String get recommendations_validation_missing_lead_name =>
      (super.noSuchMethod(
        Invocation.getter(#recommendations_validation_missing_lead_name),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#recommendations_validation_missing_lead_name),
        ),
      ) as String);

  @override
  String get recommendations_validation_missing_promoter_name =>
      (super.noSuchMethod(
        Invocation.getter(#recommendations_validation_missing_promoter_name),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#recommendations_validation_missing_promoter_name),
        ),
      ) as String);

  @override
  String get recommendations_validation_missing_reason => (super.noSuchMethod(
        Invocation.getter(#recommendations_validation_missing_reason),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#recommendations_validation_missing_reason),
        ),
      ) as String);

  @override
  String get profile_company_contact_section_title => (super.noSuchMethod(
        Invocation.getter(#profile_company_contact_section_title),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#profile_company_contact_section_title),
        ),
      ) as String);

  @override
  String get profile_company_contact_section_name => (super.noSuchMethod(
        Invocation.getter(#profile_company_contact_section_name),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#profile_company_contact_section_name),
        ),
      ) as String);

  @override
  String get profile_company_contact_section_industry => (super.noSuchMethod(
        Invocation.getter(#profile_company_contact_section_industry),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#profile_company_contact_section_industry),
        ),
      ) as String);

  @override
  String get profile_company_contact_section_website => (super.noSuchMethod(
        Invocation.getter(#profile_company_contact_section_website),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#profile_company_contact_section_website),
        ),
      ) as String);

  @override
  String get profile_company_contact_section_address => (super.noSuchMethod(
        Invocation.getter(#profile_company_contact_section_address),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#profile_company_contact_section_address),
        ),
      ) as String);

  @override
  String get profile_company_contact_section_postcode => (super.noSuchMethod(
        Invocation.getter(#profile_company_contact_section_postcode),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#profile_company_contact_section_postcode),
        ),
      ) as String);

  @override
  String get profile_company_contact_section_place => (super.noSuchMethod(
        Invocation.getter(#profile_company_contact_section_place),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#profile_company_contact_section_place),
        ),
      ) as String);

  @override
  String get profile_company_contact_section_phone => (super.noSuchMethod(
        Invocation.getter(#profile_company_contact_section_phone),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#profile_company_contact_section_phone),
        ),
      ) as String);

  @override
  String get profile_company_validator_missing_name => (super.noSuchMethod(
        Invocation.getter(#profile_company_validator_missing_name),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#profile_company_validator_missing_name),
        ),
      ) as String);

  @override
  String get profile_company_validator_missing_industry => (super.noSuchMethod(
        Invocation.getter(#profile_company_validator_missing_industry),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#profile_company_validator_missing_industry),
        ),
      ) as String);

  @override
  String get profile_company_validator_invalid_phone => (super.noSuchMethod(
        Invocation.getter(#profile_company_validator_invalid_phone),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#profile_company_validator_invalid_phone),
        ),
      ) as String);

  @override
  String get profile_company_validator_missing_address => (super.noSuchMethod(
        Invocation.getter(#profile_company_validator_missing_address),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#profile_company_validator_missing_address),
        ),
      ) as String);

  @override
  String get profile_company_validator_missing_postCode => (super.noSuchMethod(
        Invocation.getter(#profile_company_validator_missing_postCode),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#profile_company_validator_missing_postCode),
        ),
      ) as String);

  @override
  String get profile_company_validator_invalid_postCode => (super.noSuchMethod(
        Invocation.getter(#profile_company_validator_invalid_postCode),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#profile_company_validator_invalid_postCode),
        ),
      ) as String);

  @override
  String get profile_company_validator_missing_place => (super.noSuchMethod(
        Invocation.getter(#profile_company_validator_missing_place),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#profile_company_validator_missing_place),
        ),
      ) as String);

  @override
  String get profile_company_validator_missing_phone => (super.noSuchMethod(
        Invocation.getter(#profile_company_validator_missing_phone),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#profile_company_validator_missing_phone),
        ),
      ) as String);

  @override
  String get profile_company_contact_section_success_snackbar_message =>
      (super.noSuchMethod(
        Invocation.getter(
            #profile_company_contact_section_success_snackbar_message),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(
              #profile_company_contact_section_success_snackbar_message),
        ),
      ) as String);

  @override
  String get company_requests_overview_title => (super.noSuchMethod(
        Invocation.getter(#company_requests_overview_title),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#company_requests_overview_title),
        ),
      ) as String);

  @override
  String get admin_company_request_detail_title => (super.noSuchMethod(
        Invocation.getter(#admin_company_request_detail_title),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#admin_company_request_detail_title),
        ),
      ) as String);

  @override
  String get admin_company_request_detail_name => (super.noSuchMethod(
        Invocation.getter(#admin_company_request_detail_name),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#admin_company_request_detail_name),
        ),
      ) as String);

  @override
  String get admin_company_request_detail_industry => (super.noSuchMethod(
        Invocation.getter(#admin_company_request_detail_industry),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#admin_company_request_detail_industry),
        ),
      ) as String);

  @override
  String get admin_company_request_detail_address => (super.noSuchMethod(
        Invocation.getter(#admin_company_request_detail_address),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#admin_company_request_detail_address),
        ),
      ) as String);

  @override
  String get admin_company_request_detail_postcode => (super.noSuchMethod(
        Invocation.getter(#admin_company_request_detail_postcode),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#admin_company_request_detail_postcode),
        ),
      ) as String);

  @override
  String get admin_company_request_detail_place => (super.noSuchMethod(
        Invocation.getter(#admin_company_request_detail_place),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#admin_company_request_detail_place),
        ),
      ) as String);

  @override
  String get admin_company_request_detail_phone => (super.noSuchMethod(
        Invocation.getter(#admin_company_request_detail_phone),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#admin_company_request_detail_phone),
        ),
      ) as String);

  @override
  String get admin_company_request_detail_website => (super.noSuchMethod(
        Invocation.getter(#admin_company_request_detail_website),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#admin_company_request_detail_website),
        ),
      ) as String);

  @override
  String get admin_company_request_detail_user_title => (super.noSuchMethod(
        Invocation.getter(#admin_company_request_detail_user_title),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#admin_company_request_detail_user_title),
        ),
      ) as String);

  @override
  String get admin_company_request_detail_user_name => (super.noSuchMethod(
        Invocation.getter(#admin_company_request_detail_user_name),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#admin_company_request_detail_user_name),
        ),
      ) as String);

  @override
  String get admin_company_request_detail_user_email => (super.noSuchMethod(
        Invocation.getter(#admin_company_request_detail_user_email),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#admin_company_request_detail_user_email),
        ),
      ) as String);

  @override
  String get admin_company_request_detail_decline_button_title =>
      (super.noSuchMethod(
        Invocation.getter(#admin_company_request_detail_decline_button_title),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#admin_company_request_detail_decline_button_title),
        ),
      ) as String);

  @override
  String get admin_company_request_detail_accept_button_title =>
      (super.noSuchMethod(
        Invocation.getter(#admin_company_request_detail_accept_button_title),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#admin_company_request_detail_accept_button_title),
        ),
      ) as String);

  @override
  String get admin_company_request_overview_from_user => (super.noSuchMethod(
        Invocation.getter(#admin_company_request_overview_from_user),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#admin_company_request_overview_from_user),
        ),
      ) as String);

  @override
  String get admin_company_request_overview_empty_title => (super.noSuchMethod(
        Invocation.getter(#admin_company_request_overview_empty_title),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#admin_company_request_overview_empty_title),
        ),
      ) as String);

  @override
  String get admin_company_request_overview_empty_body => (super.noSuchMethod(
        Invocation.getter(#admin_company_request_overview_empty_body),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#admin_company_request_overview_empty_body),
        ),
      ) as String);

  @override
  String get admin_company_request_overview_title => (super.noSuchMethod(
        Invocation.getter(#admin_company_request_overview_title),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#admin_company_request_overview_title),
        ),
      ) as String);

  @override
  String get admin_company_request_overview_error => (super.noSuchMethod(
        Invocation.getter(#admin_company_request_overview_error),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#admin_company_request_overview_error),
        ),
      ) as String);

  @override
  String get company_registration_form_title => (super.noSuchMethod(
        Invocation.getter(#company_registration_form_title),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#company_registration_form_title),
        ),
      ) as String);

  @override
  String get company_registration_form_name_textfield_placeholder =>
      (super.noSuchMethod(
        Invocation.getter(
            #company_registration_form_name_textfield_placeholder),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(
              #company_registration_form_name_textfield_placeholder),
        ),
      ) as String);

  @override
  String get company_registration_form_industry_textfield_placeholder =>
      (super.noSuchMethod(
        Invocation.getter(
            #company_registration_form_industry_textfield_placeholder),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(
              #company_registration_form_industry_textfield_placeholder),
        ),
      ) as String);

  @override
  String get company_registration_form_website_textfield_placeholder =>
      (super.noSuchMethod(
        Invocation.getter(
            #company_registration_form_website_textfield_placeholder),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(
              #company_registration_form_website_textfield_placeholder),
        ),
      ) as String);

  @override
  String get company_registration_form_address_textfield_placeholder =>
      (super.noSuchMethod(
        Invocation.getter(
            #company_registration_form_address_textfield_placeholder),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(
              #company_registration_form_address_textfield_placeholder),
        ),
      ) as String);

  @override
  String get company_registration_form_postcode_textfield_placeholder =>
      (super.noSuchMethod(
        Invocation.getter(
            #company_registration_form_postcode_textfield_placeholder),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(
              #company_registration_form_postcode_textfield_placeholder),
        ),
      ) as String);

  @override
  String get company_registration_form_place_textfield_placeholder =>
      (super.noSuchMethod(
        Invocation.getter(
            #company_registration_form_place_textfield_placeholder),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(
              #company_registration_form_place_textfield_placeholder),
        ),
      ) as String);

  @override
  String get company_registration_form_phone_textfield_placeholder =>
      (super.noSuchMethod(
        Invocation.getter(
            #company_registration_form_phone_textfield_placeholder),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(
              #company_registration_form_phone_textfield_placeholder),
        ),
      ) as String);

  @override
  String get company_registration_form_register_button_title =>
      (super.noSuchMethod(
        Invocation.getter(#company_registration_form_register_button_title),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#company_registration_form_register_button_title),
        ),
      ) as String);

  @override
  String get profile_register_company_section_title => (super.noSuchMethod(
        Invocation.getter(#profile_register_company_section_title),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#profile_register_company_section_title),
        ),
      ) as String);

  @override
  String get profile_register_company_section_subtitle_in_progress =>
      (super.noSuchMethod(
        Invocation.getter(
            #profile_register_company_section_subtitle_in_progress),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(
              #profile_register_company_section_subtitle_in_progress),
        ),
      ) as String);

  @override
  String get profile_register_company_section_subtitle_requested_at =>
      (super.noSuchMethod(
        Invocation.getter(
            #profile_register_company_section_subtitle_requested_at),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(
              #profile_register_company_section_subtitle_requested_at),
        ),
      ) as String);

  @override
  String get profile_register_company_section_subtitle => (super.noSuchMethod(
        Invocation.getter(#profile_register_company_section_subtitle),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#profile_register_company_section_subtitle),
        ),
      ) as String);

  @override
  String get profile_register_company_section_button_title =>
      (super.noSuchMethod(
        Invocation.getter(#profile_register_company_section_button_title),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#profile_register_company_section_button_title),
        ),
      ) as String);

  @override
  String get profile_image_upload_tooltip => (super.noSuchMethod(
        Invocation.getter(#profile_image_upload_tooltip),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#profile_image_upload_tooltip),
        ),
      ) as String);

  @override
  String get landingpage_overview_edit_tooltip => (super.noSuchMethod(
        Invocation.getter(#landingpage_overview_edit_tooltip),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#landingpage_overview_edit_tooltip),
        ),
      ) as String);

  @override
  String get landingpage_overview_show_tooltip => (super.noSuchMethod(
        Invocation.getter(#landingpage_overview_show_tooltip),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#landingpage_overview_show_tooltip),
        ),
      ) as String);

  @override
  String get profile_edit_email_tooltip => (super.noSuchMethod(
        Invocation.getter(#profile_edit_email_tooltip),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#profile_edit_email_tooltip),
        ),
      ) as String);

  @override
  String get theme_switch_lightmode_tooltip => (super.noSuchMethod(
        Invocation.getter(#theme_switch_lightmode_tooltip),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#theme_switch_lightmode_tooltip),
        ),
      ) as String);

  @override
  String get theme_switch_darkmode_tooltip => (super.noSuchMethod(
        Invocation.getter(#theme_switch_darkmode_tooltip),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#theme_switch_darkmode_tooltip),
        ),
      ) as String);

  @override
  String get promoter_overview_reset_search_tooltip => (super.noSuchMethod(
        Invocation.getter(#promoter_overview_reset_search_tooltip),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#promoter_overview_reset_search_tooltip),
        ),
      ) as String);

  @override
  String get promoter_overview_filter_tooltip => (super.noSuchMethod(
        Invocation.getter(#promoter_overview_filter_tooltip),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#promoter_overview_filter_tooltip),
        ),
      ) as String);

  @override
  String get promoter_overview_view_switch_grid_tooltip => (super.noSuchMethod(
        Invocation.getter(#promoter_overview_view_switch_grid_tooltip),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#promoter_overview_view_switch_grid_tooltip),
        ),
      ) as String);

  @override
  String get promoter_overview_view_switch_table_tooltip => (super.noSuchMethod(
        Invocation.getter(#promoter_overview_view_switch_table_tooltip),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#promoter_overview_view_switch_table_tooltip),
        ),
      ) as String);

  @override
  String get recommendations_form_add_button_tooltip => (super.noSuchMethod(
        Invocation.getter(#recommendations_form_add_button_tooltip),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#recommendations_form_add_button_tooltip),
        ),
      ) as String);

  @override
  String get landingpage_pagebuilder_container_request_error =>
      (super.noSuchMethod(
        Invocation.getter(#landingpage_pagebuilder_container_request_error),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#landingpage_pagebuilder_container_request_error),
        ),
      ) as String);

  @override
  String get landingpage_pagebuilder_container_permission_error_title =>
      (super.noSuchMethod(
        Invocation.getter(
            #landingpage_pagebuilder_container_permission_error_title),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(
              #landingpage_pagebuilder_container_permission_error_title),
        ),
      ) as String);

  @override
  String get landingpage_pagebuilder_container_permission_error_message =>
      (super.noSuchMethod(
        Invocation.getter(
            #landingpage_pagebuilder_container_permission_error_message),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(
              #landingpage_pagebuilder_container_permission_error_message),
        ),
      ) as String);

  @override
  String get landingpage_pagebuilder_appbar_save_button_title =>
      (super.noSuchMethod(
        Invocation.getter(#landingpage_pagebuilder_appbar_save_button_title),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#landingpage_pagebuilder_appbar_save_button_title),
        ),
      ) as String);

  @override
  String get landingpage_pagebuilder_save_error_alert_title =>
      (super.noSuchMethod(
        Invocation.getter(#landingpage_pagebuilder_save_error_alert_title),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#landingpage_pagebuilder_save_error_alert_title),
        ),
      ) as String);

  @override
  String get landingpage_pagebuilder_save_error_alert_message =>
      (super.noSuchMethod(
        Invocation.getter(#landingpage_pagebuilder_save_error_alert_message),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#landingpage_pagebuilder_save_error_alert_message),
        ),
      ) as String);

  @override
  String get landingpage_pagebuilder_save_error_alert_button =>
      (super.noSuchMethod(
        Invocation.getter(#landingpage_pagebuilder_save_error_alert_button),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#landingpage_pagebuilder_save_error_alert_button),
        ),
      ) as String);

  @override
  String get landingpage_pagebuilder_save_success_snackbar =>
      (super.noSuchMethod(
        Invocation.getter(#landingpage_pagebuilder_save_success_snackbar),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#landingpage_pagebuilder_save_success_snackbar),
        ),
      ) as String);

  @override
  String get landingpage_pagebuilder_image_upload_exceeds_file_size_error =>
      (super.noSuchMethod(
        Invocation.getter(
            #landingpage_pagebuilder_image_upload_exceeds_file_size_error),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(
              #landingpage_pagebuilder_image_upload_exceeds_file_size_error),
        ),
      ) as String);

  @override
  String promoter_overview_expiration_date(String? date) => (super.noSuchMethod(
        Invocation.method(
          #promoter_overview_expiration_date,
          [date],
        ),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.method(
            #promoter_overview_expiration_date,
            [date],
          ),
        ),
      ) as String);

  @override
  String promoter_overview_creation_date(String? date) => (super.noSuchMethod(
        Invocation.method(
          #promoter_overview_creation_date,
          [date],
        ),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.method(
            #promoter_overview_creation_date,
            [date],
          ),
        ),
      ) as String);
}
