// Mocks generated by Mockito 5.4.4 from annotations
// in finanzbegleiter/test/repositories/auth_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:finanzbegleiter/core/failures/auth_failures.dart' as _i6;
import 'package:finanzbegleiter/core/failures/database_failures.dart' as _i8;
import 'package:finanzbegleiter/domain/entities/user.dart' as _i7;
import 'package:finanzbegleiter/domain/repositories/auth_repository.dart'
    as _i3;
import 'package:firebase_auth/firebase_auth.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOption_1<A> extends _i1.SmartFake implements _i2.Option<A> {
  _FakeOption_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i5.User?> observeAuthState() => (super.noSuchMethod(
        Invocation.method(
          #observeAuthState,
          [],
        ),
        returnValue: _i4.Stream<_i5.User?>.empty(),
      ) as _i4.Stream<_i5.User?>);

  @override
  _i4.Future<_i2.Either<_i6.AuthFailure, _i5.UserCredential>>
      registerWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #registerWithEmailAndPassword,
              [],
              {
                #email: email,
                #password: password,
              },
            ),
            returnValue: _i4
                .Future<_i2.Either<_i6.AuthFailure, _i5.UserCredential>>.value(
                _FakeEither_0<_i6.AuthFailure, _i5.UserCredential>(
              this,
              Invocation.method(
                #registerWithEmailAndPassword,
                [],
                {
                  #email: email,
                  #password: password,
                },
              ),
            )),
          ) as _i4.Future<_i2.Either<_i6.AuthFailure, _i5.UserCredential>>);

  @override
  _i4.Future<_i2.Either<_i6.AuthFailure, _i5.UserCredential>>
      loginWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #loginWithEmailAndPassword,
              [],
              {
                #email: email,
                #password: password,
              },
            ),
            returnValue: _i4
                .Future<_i2.Either<_i6.AuthFailure, _i5.UserCredential>>.value(
                _FakeEither_0<_i6.AuthFailure, _i5.UserCredential>(
              this,
              Invocation.method(
                #loginWithEmailAndPassword,
                [],
                {
                  #email: email,
                  #password: password,
                },
              ),
            )),
          ) as _i4.Future<_i2.Either<_i6.AuthFailure, _i5.UserCredential>>);

  @override
  _i4.Future<_i2.Either<_i6.AuthFailure, _i5.UserCredential>>
      reauthenticateWithPassword({required String? password}) =>
          (super.noSuchMethod(
            Invocation.method(
              #reauthenticateWithPassword,
              [],
              {#password: password},
            ),
            returnValue: _i4
                .Future<_i2.Either<_i6.AuthFailure, _i5.UserCredential>>.value(
                _FakeEither_0<_i6.AuthFailure, _i5.UserCredential>(
              this,
              Invocation.method(
                #reauthenticateWithPassword,
                [],
                {#password: password},
              ),
            )),
          ) as _i4.Future<_i2.Either<_i6.AuthFailure, _i5.UserCredential>>);

  @override
  _i4.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i2.Option<_i7.CustomUser> getSignedInUser() => (super.noSuchMethod(
        Invocation.method(
          #getSignedInUser,
          [],
        ),
        returnValue: _FakeOption_1<_i7.CustomUser>(
          this,
          Invocation.method(
            #getSignedInUser,
            [],
          ),
        ),
      ) as _i2.Option<_i7.CustomUser>);

  @override
  _i4.Future<void> resendEmailVerification() => (super.noSuchMethod(
        Invocation.method(
          #resendEmailVerification,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.Either<_i6.AuthFailure, void>> resetPassword(
          {required String? email}) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [],
          {#email: email},
        ),
        returnValue: _i4.Future<_i2.Either<_i6.AuthFailure, void>>.value(
            _FakeEither_0<_i6.AuthFailure, void>(
          this,
          Invocation.method(
            #resetPassword,
            [],
            {#email: email},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.AuthFailure, void>>);

  @override
  _i4.Future<_i2.Either<_i8.DatabaseFailure, bool>> isRegistrationCodeValid({
    required String? email,
    required String? code,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #isRegistrationCodeValid,
          [],
          {
            #email: email,
            #code: code,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i8.DatabaseFailure, bool>>.value(
            _FakeEither_0<_i8.DatabaseFailure, bool>(
          this,
          Invocation.method(
            #isRegistrationCodeValid,
            [],
            {
              #email: email,
              #code: code,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i8.DatabaseFailure, bool>>);

  @override
  _i4.Future<_i2.Either<_i6.AuthFailure, _i2.Unit>> deleteAccount() =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAccount,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.AuthFailure, _i2.Unit>>.value(
            _FakeEither_0<_i6.AuthFailure, _i2.Unit>(
          this,
          Invocation.method(
            #deleteAccount,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.AuthFailure, _i2.Unit>>);
}
