// Mocks generated by Mockito 5.4.4 from annotations
// in finanzbegleiter/test/repositories/company_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:finanzbegleiter/core/failures/database_failures.dart' as _i5;
import 'package:finanzbegleiter/domain/entities/company.dart' as _i6;
import 'package:finanzbegleiter/domain/entities/company_request.dart' as _i7;
import 'package:finanzbegleiter/domain/repositories/company_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CompanyRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCompanyRepository extends _i1.Mock implements _i3.CompanyRepository {
  MockCompanyRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i2.Either<_i5.DatabaseFailure, _i6.Company>> observeCompany(
          String? companyID) =>
      (super.noSuchMethod(
        Invocation.method(
          #observeCompany,
          [companyID],
        ),
        returnValue:
            _i4.Stream<_i2.Either<_i5.DatabaseFailure, _i6.Company>>.empty(),
      ) as _i4.Stream<_i2.Either<_i5.DatabaseFailure, _i6.Company>>);

  @override
  _i4.Future<_i2.Either<_i5.DatabaseFailure, _i2.Unit>> updateCompany(
          _i6.Company? company) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCompany,
          [company],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.DatabaseFailure, _i2.Unit>>.value(
                _FakeEither_0<_i5.DatabaseFailure, _i2.Unit>(
          this,
          Invocation.method(
            #updateCompany,
            [company],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.DatabaseFailure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.DatabaseFailure, _i6.Company>> getCompany(
          String? companyID) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCompany,
          [companyID],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.DatabaseFailure, _i6.Company>>.value(
                _FakeEither_0<_i5.DatabaseFailure, _i6.Company>(
          this,
          Invocation.method(
            #getCompany,
            [companyID],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.DatabaseFailure, _i6.Company>>);

  @override
  _i4.Future<_i2.Either<_i5.DatabaseFailure, _i2.Unit>> registerCompany(
          _i6.Company? company) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerCompany,
          [company],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.DatabaseFailure, _i2.Unit>>.value(
                _FakeEither_0<_i5.DatabaseFailure, _i2.Unit>(
          this,
          Invocation.method(
            #registerCompany,
            [company],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.DatabaseFailure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.DatabaseFailure, _i7.CompanyRequest>>
      getPendingCompanyRequest(String? id) => (super.noSuchMethod(
            Invocation.method(
              #getPendingCompanyRequest,
              [id],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.DatabaseFailure, _i7.CompanyRequest>>.value(
                _FakeEither_0<_i5.DatabaseFailure, _i7.CompanyRequest>(
              this,
              Invocation.method(
                #getPendingCompanyRequest,
                [id],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.DatabaseFailure, _i7.CompanyRequest>>);
}
