// Mocks generated by Mockito 5.4.4 from annotations
// in finanzbegleiter/test/repositories/landingpage_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i8;

import 'package:dartz/dartz.dart' as _i2;
import 'package:finanzbegleiter/core/failures/database_failures.dart' as _i5;
import 'package:finanzbegleiter/domain/entities/landing_page.dart' as _i7;
import 'package:finanzbegleiter/domain/entities/user.dart' as _i6;
import 'package:finanzbegleiter/domain/repositories/landing_page_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LandingPageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLandingPageRepository extends _i1.Mock
    implements _i3.LandingPageRepository {
  MockLandingPageRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i2.Either<_i5.DatabaseFailure, _i6.CustomUser>>
      observeAllLandingPages() => (super.noSuchMethod(
            Invocation.method(
              #observeAllLandingPages,
              [],
            ),
            returnValue: _i4.Stream<
                _i2.Either<_i5.DatabaseFailure, _i6.CustomUser>>.empty(),
          ) as _i4.Stream<_i2.Either<_i5.DatabaseFailure, _i6.CustomUser>>);

  @override
  _i4.Future<_i2.Either<_i5.DatabaseFailure, List<_i7.LandingPage>>>
      getAllLandingPages(List<String>? ids) => (super.noSuchMethod(
            Invocation.method(
              #getAllLandingPages,
              [ids],
            ),
            returnValue: _i4.Future<
                    _i2
                    .Either<_i5.DatabaseFailure, List<_i7.LandingPage>>>.value(
                _FakeEither_0<_i5.DatabaseFailure, List<_i7.LandingPage>>(
              this,
              Invocation.method(
                #getAllLandingPages,
                [ids],
              ),
            )),
          ) as _i4
              .Future<_i2.Either<_i5.DatabaseFailure, List<_i7.LandingPage>>>);

  @override
  _i4.Future<_i2.Either<_i5.DatabaseFailure, _i2.Unit>> createLandingPage(
    _i7.LandingPage? landingPage,
    _i8.Uint8List? imageData,
    bool? imageHasChanged,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createLandingPage,
          [
            landingPage,
            imageData,
            imageHasChanged,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.DatabaseFailure, _i2.Unit>>.value(
                _FakeEither_0<_i5.DatabaseFailure, _i2.Unit>(
          this,
          Invocation.method(
            #createLandingPage,
            [
              landingPage,
              imageData,
              imageHasChanged,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.DatabaseFailure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.DatabaseFailure, _i2.Unit>> deleteLandingPage(
    String? id,
    String? ownerID,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteLandingPage,
          [
            id,
            ownerID,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.DatabaseFailure, _i2.Unit>>.value(
                _FakeEither_0<_i5.DatabaseFailure, _i2.Unit>(
          this,
          Invocation.method(
            #deleteLandingPage,
            [
              id,
              ownerID,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.DatabaseFailure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.DatabaseFailure, _i2.Unit>> editLandingPage(
    _i7.LandingPage? landingPage,
    _i8.Uint8List? imageData,
    bool? imageHasChanged,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #editLandingPage,
          [
            landingPage,
            imageData,
            imageHasChanged,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.DatabaseFailure, _i2.Unit>>.value(
                _FakeEither_0<_i5.DatabaseFailure, _i2.Unit>(
          this,
          Invocation.method(
            #editLandingPage,
            [
              landingPage,
              imageData,
              imageHasChanged,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.DatabaseFailure, _i2.Unit>>);
}
