// Mocks generated by Mockito 5.4.4 from annotations
// in finanzbegleiter/test/repositories/promoter_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:finanzbegleiter/core/failures/database_failures.dart' as _i5;
import 'package:finanzbegleiter/domain/entities/unregistered_promoter.dart'
    as _i6;
import 'package:finanzbegleiter/domain/entities/user.dart' as _i7;
import 'package:finanzbegleiter/domain/repositories/promoter_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PromoterRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPromoterRepository extends _i1.Mock
    implements _i3.PromoterRepository {
  MockPromoterRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.DatabaseFailure, _i2.Unit>> registerPromoter(
          {required _i6.UnregisteredPromoter? promoter}) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerPromoter,
          [],
          {#promoter: promoter},
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.DatabaseFailure, _i2.Unit>>.value(
                _FakeEither_0<_i5.DatabaseFailure, _i2.Unit>(
          this,
          Invocation.method(
            #registerPromoter,
            [],
            {#promoter: promoter},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.DatabaseFailure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.DatabaseFailure, bool>>
      checkIfPromoterAlreadyExists({required String? email}) =>
          (super.noSuchMethod(
            Invocation.method(
              #checkIfPromoterAlreadyExists,
              [],
              {#email: email},
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.DatabaseFailure, bool>>.value(
                    _FakeEither_0<_i5.DatabaseFailure, bool>(
              this,
              Invocation.method(
                #checkIfPromoterAlreadyExists,
                [],
                {#email: email},
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.DatabaseFailure, bool>>);

  @override
  _i4.Stream<_i2.Either<_i5.DatabaseFailure, _i7.CustomUser>>
      observeAllPromoters() => (super.noSuchMethod(
            Invocation.method(
              #observeAllPromoters,
              [],
            ),
            returnValue: _i4.Stream<
                _i2.Either<_i5.DatabaseFailure, _i7.CustomUser>>.empty(),
          ) as _i4.Stream<_i2.Either<_i5.DatabaseFailure, _i7.CustomUser>>);

  @override
  _i4.Future<_i2.Either<_i5.DatabaseFailure, List<_i7.CustomUser>>>
      getRegisteredPromoters(List<String>? ids) => (super.noSuchMethod(
            Invocation.method(
              #getRegisteredPromoters,
              [ids],
            ),
            returnValue: _i4.Future<
                    _i2
                    .Either<_i5.DatabaseFailure, List<_i7.CustomUser>>>.value(
                _FakeEither_0<_i5.DatabaseFailure, List<_i7.CustomUser>>(
              this,
              Invocation.method(
                #getRegisteredPromoters,
                [ids],
              ),
            )),
          ) as _i4
              .Future<_i2.Either<_i5.DatabaseFailure, List<_i7.CustomUser>>>);

  @override
  _i4.Future<_i2.Either<_i5.DatabaseFailure, List<_i6.UnregisteredPromoter>>>
      getUnregisteredPromoters(List<String>? ids) => (super.noSuchMethod(
            Invocation.method(
              #getUnregisteredPromoters,
              [ids],
            ),
            returnValue: _i4.Future<
                _i2.Either<_i5.DatabaseFailure,
                    List<_i6.UnregisteredPromoter>>>.value(_FakeEither_0<
                _i5.DatabaseFailure, List<_i6.UnregisteredPromoter>>(
              this,
              Invocation.method(
                #getUnregisteredPromoters,
                [ids],
              ),
            )),
          ) as _i4.Future<
              _i2.Either<_i5.DatabaseFailure, List<_i6.UnregisteredPromoter>>>);
}
