// Mocks generated by Mockito 5.4.4 from annotations
// in finanzbegleiter/test/repositories/user_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:finanzbegleiter/core/failures/auth_failures.dart' as _i7;
import 'package:finanzbegleiter/core/failures/database_failures.dart' as _i5;
import 'package:finanzbegleiter/domain/entities/user.dart' as _i6;
import 'package:finanzbegleiter/domain/repositories/user_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i3.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i2.Either<_i5.DatabaseFailure, _i6.CustomUser>> observeUser() =>
      (super.noSuchMethod(
        Invocation.method(
          #observeUser,
          [],
        ),
        returnValue:
            _i4.Stream<_i2.Either<_i5.DatabaseFailure, _i6.CustomUser>>.empty(),
      ) as _i4.Stream<_i2.Either<_i5.DatabaseFailure, _i6.CustomUser>>);

  @override
  _i4.Future<_i2.Either<_i5.DatabaseFailure, _i2.Unit>> createUser(
          {required _i6.CustomUser? user}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createUser,
          [],
          {#user: user},
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.DatabaseFailure, _i2.Unit>>.value(
                _FakeEither_0<_i5.DatabaseFailure, _i2.Unit>(
          this,
          Invocation.method(
            #createUser,
            [],
            {#user: user},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.DatabaseFailure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.DatabaseFailure, _i2.Unit>> updateUser(
          {required _i6.CustomUser? user}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUser,
          [],
          {#user: user},
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.DatabaseFailure, _i2.Unit>>.value(
                _FakeEither_0<_i5.DatabaseFailure, _i2.Unit>(
          this,
          Invocation.method(
            #updateUser,
            [],
            {#user: user},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.DatabaseFailure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i7.AuthFailure, void>> updateEmail(
          {required String? email}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateEmail,
          [],
          {#email: email},
        ),
        returnValue: _i4.Future<_i2.Either<_i7.AuthFailure, void>>.value(
            _FakeEither_0<_i7.AuthFailure, void>(
          this,
          Invocation.method(
            #updateEmail,
            [],
            {#email: email},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i7.AuthFailure, void>>);

  @override
  _i4.Future<bool> isEmailVerified() => (super.noSuchMethod(
        Invocation.method(
          #isEmailVerified,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<_i2.Either<_i7.AuthFailure, void>> updatePassword(
          {required String? password}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePassword,
          [],
          {#password: password},
        ),
        returnValue: _i4.Future<_i2.Either<_i7.AuthFailure, void>>.value(
            _FakeEither_0<_i7.AuthFailure, void>(
          this,
          Invocation.method(
            #updatePassword,
            [],
            {#password: password},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i7.AuthFailure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.DatabaseFailure, _i6.CustomUser>> getUser() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUser,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.DatabaseFailure, _i6.CustomUser>>.value(
                _FakeEither_0<_i5.DatabaseFailure, _i6.CustomUser>(
          this,
          Invocation.method(
            #getUser,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.DatabaseFailure, _i6.CustomUser>>);

  @override
  _i4.Future<_i2.Either<_i5.DatabaseFailure, _i6.CustomUser>> getParentUser(
          {required String? parentID}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getParentUser,
          [],
          {#parentID: parentID},
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.DatabaseFailure, _i6.CustomUser>>.value(
                _FakeEither_0<_i5.DatabaseFailure, _i6.CustomUser>(
          this,
          Invocation.method(
            #getParentUser,
            [],
            {#parentID: parentID},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.DatabaseFailure, _i6.CustomUser>>);
}
